 # .goreleaser.yml for CLI application package
# Replace 'your-cli-name' with your actual CLI application name

project_name: your-cli-name
version: 2

# Distribution directory
dist: tmp/dist

# Build destination
github_urls:
  # set to true if you use a self-signed certificate
  skip_tls_verify: false

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - main: cmd/main.go
    id: your-cli-name
    binary: your-cli-name
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
    ldflags:
      - -X 'github.com/yourorg/your-cli-name/pkg/version.Version={{ .Version }}'

archives:
  - name_template: '{{ .ProjectName }}-v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - "*.go"
      - "*.md"
      - "go.mod"
      - "go.sum"
      - "LICENSE"

# Docker configuration
# Replace 'yourorg' with your actual GitHub organization/username
dockers:
  - image_templates:
      - "ghcr.io/yourorg/your-cli-name:latest-amd64"
      - "ghcr.io/yourorg/your-cli-name:{{ .Tag }}-amd64"
      - "ghcr.io/yourorg/your-cli-name:v{{ .Major }}-amd64"
      - "ghcr.io/yourorg/your-cli-name:v{{ .Major }}.{{ .Minor }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=CLI tool for your application"
      - "--label=org.opencontainers.image.url=https://github.com/yourorg/your-cli-name"
      - "--label=org.opencontainers.image.source=https://github.com/yourorg/your-cli-name"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"
    extra_files:
      - go.mod
      - go.sum
      - cmd/
      - internal/
      - pkg/
    goarch: amd64
  - image_templates:
      - "ghcr.io/yourorg/your-cli-name:latest-arm64"
      - "ghcr.io/yourorg/your-cli-name:{{ .Tag }}-arm64"
      - "ghcr.io/yourorg/your-cli-name:v{{ .Major }}-arm64"
      - "ghcr.io/yourorg/your-cli-name:v{{ .Major }}.{{ .Minor }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description=CLI tool for your application"
      - "--label=org.opencontainers.image.url=https://github.com/yourorg/your-cli-name"
      - "--label=org.opencontainers.image.source=https://github.com/yourorg/your-cli-name"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"
    extra_files:
      - go.mod
      - go.sum
      - cmd/
      - internal/
      - pkg/
    goarch: arm64

# Docker manifest for multi-platform images
docker_manifests:
  - name_template: "ghcr.io/yourorg/your-cli-name:latest"
    image_templates:
      - "ghcr.io/yourorg/your-cli-name:latest-amd64"
      - "ghcr.io/yourorg/your-cli-name:latest-arm64"
  - name_template: "ghcr.io/yourorg/your-cli-name:{{ .Tag }}"
    image_templates:
      - "ghcr.io/yourorg/your-cli-name:{{ .Tag }}-amd64"
      - "ghcr.io/yourorg/your-cli-name:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/yourorg/your-cli-name:v{{ .Major }}"
    image_templates:
      - "ghcr.io/yourorg/your-cli-name:v{{ .Major }}-amd64"
      - "ghcr.io/yourorg/your-cli-name:v{{ .Major }}-arm64"
  - name_template: "ghcr.io/yourorg/your-cli-name:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/yourorg/your-cli-name:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/yourorg/your-cli-name:v{{ .Major }}.{{ .Minor }}-arm64"

release:
  prerelease: auto
  draft: false
  replace_existing_draft: true
  header: |
    ## {{ .ProjectName }} v{{ .Version }}

    This release contains the CLI for your application.

    ### 🐳 Container Images
    ```bash
    # Latest version
    docker run --rm ghcr.io/yourorg/your-cli-name:latest --help

    # Specific version
    docker run --rm ghcr.io/yourorg/your-cli-name:{{ .Tag }} command --help

    # With environment variables
    docker run --rm -e YOUR_CLI_ENV="value" ghcr.io/yourorg/your-cli-name:{{ .Tag }} command
    ```

    ### 📦 Binary Installation
    ```bash
    go install github.com/yourorg/your-cli-name@v{{ .Version }}
    ```

  footer: |
    **Full Changelog**: https://github.com/yourorg/your-cli-name/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### 📚 Documentation
    - [README](https://github.com/yourorg/your-cli-name/blob/{{ .Tag }}/README.md)
    - [CLI Reference](https://github.com/yourorg/your-cli-name/blob/{{ .Tag }}/docs/CLI_REFERENCE.md)
    - [Container Registry](https://github.com/yourorg/your-cli-name/pkgs/container/your-cli-name)

# Generate checksums for source archives
checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}_checksums.txt"

# Changelog configuration
changelog:
  use: github
  sort: asc
  abbrev: 0
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Documentation updates
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Other work
      order: 999
  filters:
    exclude:
      - '^test:'
      - '^chore:'
      - '^ci:'

# Metadata for Go proxy and pkg.go.dev
metadata:
  mod_timestamp: '{{ .CommitTimestamp }}'
