name: Reusable GoReleaser Workflow

# Required permissions for calling workflow:
# permissions:
#   contents: write      # For creating releases
#   packages: write      # For pushing to ghcr.io
#   id-token: write      # For OIDC authentication

on:
  workflow_call:
    inputs:
      go_version:
        description: "Go version to use"
        required: false
        type: string
        default: "1.24.5"
      goreleaser_version:
        description: "GoReleaser version to use"
        required: false
        type: string
        default: "latest"
      goreleaser_args:
        description: "GoReleaser arguments"
        required: false
        type: string
        default: "release --clean"
      runs_on:
        description: "Runner to use for the job"
        required: false
        type: string
        default: "ubuntu-24.04"
      fetch_depth:
        description: "Number of commits to fetch (0 = all history)"
        required: false
        type: number
        default: 0
      enable_docker:
        description: "Enable Docker Buildx setup"
        required: false
        type: boolean
        default: true
      registry:
        description: "Container registry to use"
        required: false
        type: string
        default: "ghcr.io"
      goreleaser_distribution:
        description: "GoReleaser distribution"
        required: false
        type: string
        default: "goreleaser"

jobs:
  goreleaser:
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: ${{ inputs.fetch_depth }}

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ inputs.go_version }}

      - name: Set up Docker Buildx
        if: ${{ inputs.enable_docker }}
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Login to Container Registry
        if: ${{ inputs.enable_docker }}
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6.3.0
        with:
          distribution: ${{ inputs.goreleaser_distribution }}
          version: ${{ inputs.goreleaser_version }}
          args: ${{ inputs.goreleaser_args }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
