name: Internal Notify Workflow Failure

on:
  workflow_run:
    workflows:
      [
        "Internal CodeQL Analysis",
        "Internal actionlint",
        "Internal markdownlint",
        "Internal Link Check",
      ]
    types: ["completed"]

permissions:
  contents: read

jobs:
  notify:
    if: github.event.workflow_run.event == 'schedule' && github.event.workflow_run.conclusion == 'failure'
    permissions:
      issues: write
    uses: ./.github/workflows/notify-workflow-failure.yml
    with:
      workflow_name: ${{ github.event.workflow_run.name }}
      run_url: ${{ github.event.workflow_run.html_url }}
