name: Update Tag on VERSION Change

on:
  push:
    branches:
      - main
    paths:
      - VERSION

permissions:
  contents: write

jobs:
  tag:
    uses: umatare5/common/.github/workflows/tagging.yml@c70780f0ddb98d15dbdc6b2a89cf01f766c65b7d # v0.9.0
