name: Internal markdownlint

on:
  push:
    paths:
      - "**/*.md"
      - ".markdownlint-cli2.jsonc"
      - ".github/workflows/markdownlint.yml"
  pull_request:
    paths:
      - "**/*.md"
      - ".markdownlint-cli2.jsonc"
      - ".github/workflows/markdownlint.yml"

permissions:
  contents: read

jobs:
  markdownlint:
    uses: ./.github/workflows/markdownlint.yml
