name: Internal Link Check

on:
  push:
    paths:
      - "**/*.md"
      - "lychee.toml"
      - ".github/workflows/lychee.yml"
  pull_request:
    paths:
      - "**/*.md"
      - "lychee.toml"
      - ".github/workflows/lychee.yml"

permissions:
  contents: read

jobs:
  lychee:
    uses: ./.github/workflows/lychee.yml
