name: Update Tag on VERSION Change

on:
  push:
    branches:
      - main
    paths:
      - VERSION

permissions:
  contents: write

jobs:
  tag:
    uses: umatare5/common/.github/workflows/tagging.yml@ae7dde8aa1448a79660db0d935bbf865d85f58c5 # v0.17.0
