name: Update Tag on VERSION Change

on:
  push:
    branches:
      - main
    paths:
      - VERSION

permissions:
  contents: write

jobs:
  tag:
    uses: umatare5/common/.github/workflows/tagging.yml@3df623d482350006c12656381399db14f8879fcc # v0.19.0
