name: Update Tag on VERSION Change

on:
  push:
    branches:
      - main
    paths:
      - VERSION

permissions:
  contents: write

jobs:
  tag:
    uses: umatare5/common/.github/workflows/tagging.yml@08e590dd16d0e7dd50ac124c72429868458dee9f
